version: '3.8'
services:
  nginx-block:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-block
    restart: unless-stopped
    ports: 
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/test.conf:/etc/nginx/conf.d/test.conf
      #一個一個加,否則blacklist檔案會被蓋掉
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
  